import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header';
import type { Metadata } from "next";

export const metadata: Metadata = {
  metadataBase: new URL("https://your-domain.com"),

  title: {
    default: "YourStory",
    template: "%s | YourStory",
  },

  description:
    "A modern platform for sharing stories, articles and ideas.",

  openGraph: {
    title: "YourStory",
    description:
      "A modern platform for sharing stories, articles and ideas.",

    type: "website",

    locale: "id_ID",

    siteName: "YourStory",
  },

  twitter: {
    card: "summary_large_image",
    title: "YourStory",
    description:
      "A modern platform for sharing stories, articles and ideas.",
  },
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Artikel",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <body>{children}</body>
    </html>
  );
}
